name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version:  ${{ matrix.node-version }}
          cache: "npm"
      - run: corepack enable

      - name: Install deps
        run: npm install --frozen-lockfile

      # Load every key in .env.example (all are safe placeholders)
      - name: Load defaults from .env.example
        id: load_env
        run: |
          set -o allexport      # export each line as an env var
          source .env.example   # ignores comments / empty lines
          set +o allexport
        shell: bash

      # Overlay the real secrets
      #     These *replace* the placeholders for the same keys
      - name: Validate environment variables
        env:
          # real secrets (configured in repo → Settings → Secrets and variables)
          SHOPIFY_API_KEY:    ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_API_SECRET: ${{ secrets.SHOPIFY_API_SECRET }}
          DATABASE_URL:       ${{ secrets.DATABASE_URL }}

          # any public value that ought to be shared can stay in .env.example
          # but you can still override it here if necessary
        run: npm exec ts-node app/env.server.ts
        # If validation passes the job continues; if not, CI fails here

      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test -- --runInBand
      - name: Build
        run: npm run build
