name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version:  ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci                  # deterministic, lock-file only

      # Load every key in .env.example (all are safe placeholders)
      - name: Load defaults from .env.example
        id: load_env
        run: |
          set -o allexport
          source .env.example
          set +o allexport
        shell: bash

      # Overlay the real secrets
      #     These *replace* the placeholders for the same keys
      - name: Validate environment variables
        env:
          SHOPIFY_API_KEY:    ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_API_SECRET: ${{ secrets.SHOPIFY_API_SECRET }}
          DATABASE_URL:       ${{ secrets.DATABASE_URL }}
        run: npx ts-node-esm app/env.server.ts 

      # Quality gates
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test -- --runInBand
      - name: Build
        run: npm run build
